config/routes.rb
Rails.application.routes.draw do
root 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  resources :dashboard
  resources :products

  

  get 'contact_us' => 'home#contact'
  get 'terms_of_service' => 'home#service'
  post 'send_mail' => 'home#send_mail' 
  get 'send_mail' => 'home#new_mail'
  get 'admin_products_list' => 'products#adminindex'
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base


  attr_accessor :name, :email, :body

  validates :name, :email, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
mount_uploader :image, ImageUploader
validates :name, :brand, :category, :price, :image, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:firstname, :lastname, :gender, :address, :city, :mobile_no, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
    	redirect_to dashboard_index_path
    end
  end

  def contact
  end
 
  def new_mail
    @message=Message.new
  end

  def send_mail
    @message = Message.new(params[:message])
    
    puts "-------------------"
    if @message.valid?
    ContactMailer.contact_email(@message).deliver
    redirect_to contact_us_path, :notice => "Message was successfully sent."
    else
    flash.now.alert = "Please fill all fields with valid details"
    render :contact
    end
  end

  def terms
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def new
 @product=Product.new
end
def show
  @product=Product.find(params[:id])
end

def index
 if params[:request_type]=="all"
  @products= Product.all
 else
  @products= Product.where(category: params[:request_type])
  end
 
end
def edit
  @product = Product.find(params[:id])
end
def adminindex
  @products= Product.all
end 
def update
  @product=Product.find(params[:id])
  if @product.update(product_params)
    redirect_to @product
  else
    render 'edit'
  end
end

def create
  @product = Product.new(product_params)
  if @product.save
    redirect_to @product
  else
    render 'new'
  end
end
def destroy
  @product = Product.find(params[:id])
  @product.destroy
 
  redirect_to products_path
end

private
  def product_params
    params.require(:product).permit(:name, :brand, :category, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/index.html.erb
<% if (current_user.admin?) %>
  <h1 class="title">WELCOME ADMIN</h1>
  <div align="center">
    <table id="adminindex">
     <tr>
        <td class="alt"><%= link_to 'Add a new Product', new_product_path %></td>
        <td><%= link_to 'Edit a Product', admin_products_list_path %></td>
     </tr>
      <tr>
        <td ><%= link_to 'List all Products', admin_products_list_path %></td>
        <td class="alt"><%= link_to 'Delete a Product', admin_products_list_path %></td>
      </tr>
    </table>
   </div>
<% end %>

app/views/home/contact.html.erb
<body>
<h1 class="title">Contact Us</h1><br>
<div align="center">
<h4>EC_CART PVT LTD</h4>
1st FLOOR , APEX BUILDINGS, ASHOKA ROAD <br />
KALOOR , KOCHI 682017, INDIA<br/>
TEL: +91 484-6462287<br/>
info@nuventure.in<br/>
</div><br/><br/>


<div>

<%= form_for :message, url: send_mail_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :e_mail%><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.label :message %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Send Mail" %>
  </p>
<% end %>

</div>
</body>

app/views/home/index.html.erb
<link href="/assets/application.css" media="screen" rel="stylesheet" />

<body>
<div>
<h1 class="title" ><b>EC-CART</b></h1>
<h3 align="center" >Grocery Online</h3>

<p align="center"><%= a=image_tag("cart1.jpg", height: '350', width: '350') %></p>
</div>



</body>

app/views/home/service.html.erb
<h1>Terms of Service</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

<body>

<%# top menu bar included with authentication(devise) links #%>


<nav class="top-bar">
<ul class="left">
<li class="name">
  <div class="user_nav">
    <% if user_signed_in? %>
     <strong>Hello <%= current_user.firstname %></strong>&nbsp
     <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %> 
     <% else %>
     <%= link_to 'Sign up', new_user_registration_path %> | <%= link_to 'Sign in', new_user_session_path %> 
     <% end %>
  </div>
</li>
</ul>
<section class="top-bar-section">
<ul class="right">
     


 <li class="has-form"> <div class="row collapse"> 
      <div class="large-8 small-9 columns"> 
      <input type="text" placeholder="Find Product"> </div> 
      <div class="large-4 small-3 columns"> 
      <a href="#" class="alert button expand">Search</a> </div> </div> </li>

      <li class="divider"></li>
      <li><%= link_to "Home", root_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Browse Products", products_path(request_type: "all") %></li>
      <li class="divider"></li>
      <li><%= link_to "Terms of Service", terms_of_service_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Contact Us", contact_us_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Cart" %></li>
      
    </ul>
  </section>
</nav>

<div class="row">
  <div class="small-3 columns" style="background-color:yellow;float:left;width:150px;"> 
     <div class="nav">
     <ul class="side-nav">
     <li class="active"><%= link_to "Grocery", products_path(request_type: "aata") %>
       <ul class="square"><li>Pulses</li>
       <li>Oil & Ghee </li>
       <li>Rice & Flours </li>
       </ul>
     </li>

    <li class="divider"></li>
    <li>Dairy Products</li>
    <li class="divider"></li>
    <li>Fruits & Vegetables</li>
    <li class="divider"></li>
    <li><%= link_to "Personal & Home care", products_path(request_type: ["soap","toothpaste"]) %></li>
    </ul>
    </div>
  </div>
<div class="small-6 columns"><%= yield %></div>

<div class="small-3 columns">
  <h2 class="subheader">About Us</h2>
      We make your grocery shopping quicker,easier and happier. We facilitate you to sit at home and order the best quality grocery. Choose your favourite brands with the best offers from our full-fledged product list. We at EC-Cart assure you top quality grocery delivered at your doorstep as per your requirement.  
  <div class="row">
 
    <div class="4 columns"><h2 class="subheader">Login</h2>
    
    <a class="round button" href="http://localhost:3000/users/sign_in">Sign In</a><a class="round button" href="http://localhost:3000/users/sign_up">Sign Up</a>
    <div style="background-color:red">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %></div>
    <% end %>
    <% if user_signed_in? %>
     Signed in as <%= current_user.email %> Not you?
     <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %> <% end %>
     
   </div>
   </div>

  </div>
</div>    

</div>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
 
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
       Found <%= pluralize(@product.errors.count, "error") %>Product not added to the database.
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <p>
    <%= f.label :Product_Name %>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :Brand %>
    <%= f.text_area :brand %>
  </p>
 
  <p> 
    <%= f.label :Category %>
    <%= f.text_field :category %>
  </p>
 
  <p>
    <%= f.label :Price %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.label :image %>
    <%= f.file_field :image %>   
  </p>


  <p>
    <%= f.submit 'Add Product'%>
  </p>
<% end %>

app/views/products/adminindex.html.erb
<h1 class="title">Products</h1>
 
<table>
  <tr>
    <th>Product</th>
    <th>Price</th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag(product.image,size: "200x100") %></td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
       <td><%= link_to 'Delete', product_path(product),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/products/edit.html.erb
<h1>Editing article</h1>
 <%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class="title">Products</h1>
 
<table>
  <tr>
    <th>Product</th>
    <th>Price</th>
  </tr>

 
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag(product.image,size: "200x100") %></td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'Add to Cart' %></td>

    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1 class="title">Products list</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<br/><table border="1" align="center">
 <tr>
   <th>Product</th>
   <th>Price</th>
 </tr>
 <tr>
   <td><%= @product.name %></td>
   <td><%= @product.price %></td>
 </tr> 
 <tr>
   <td class="r", colspan="2"><%= image_tag(@product.image, size: "200x100", alt: "No image available") %></td>
 </tr>

 
 <tr><td  style="background-color:yellow", class="r", colspan="2"><%= link_to image_tag("http://favoursgroup.com/Images/Icons/RedCart.png", size: "70x70", border: 0) %>
 Add to Cart</td></tr>
</table>